### ISSUE TITLE
Tips memulai aktif di project open source?

### ISSUE THREAD

**Issue by cahyareza** [agusmakmun/askme#1]
Assalamualaikum Wr. Wb
Mas ada tips buat menghilangkan insecure kalau mau ikut project opensource ga?
Terimakasih

**Comment by agusmakmun** [comment]
Waalaikumsalam Warahmatullahi Wabarakatuh mas @cahyareza, 

Sebelumnya terimakasih banyak sudah berkunjung disini, selamat masnya menjadi orang pertama yang mengisi askme ini.. hehe 🙌 

Terkait dengan pertanyaan masnya, mungkin alangkah baiknya jika kita mengetahui dahulu beberapa keuntungan ketika aktif di project open source, diantaranya adalah:

1. **Meningkatkan Keterampilan**: Berkontribusi pada proyek open source dapat membantu kita untuk memperluas keterampilan teknis, dapat belajar hal-hal baru, kerangka kerja, alat pengembangan, dan praktik terbaik dalam pengembangan perangkat lunak. Ini juga bisa membantu kita memperoleh pengalaman nyata dalam pengembangan perangkat lunak, terutama di dunia kerja.

2. **Meningkatkan Reputasi/Portofolio**: Selain itu juga dapat membantu kita meningkatkan reputasi bahkan portofolio kita sendiri. Sebagai contoh realnya di dunia kerja *terutama ketika tahapan interview, biasanya ditanyakan apa punya github, stackoverflow atau yg lainnya. Dan itu sangat menjadi nilai plus ➕ dibandingkan dengan beberapa portofolio/resume yang tidak memiliki.

3. **Meningkatkan Jaringan**: Berkontribusi pada proyek open source dapat membantu kita terhubung dengan orang-orang yang memiliki minat dan tujuan yang sama. Ini bisa membuka pintu untuk peluang kerja baru atau bahkan membantu kita menemukan teman dan mentor baru. Dan dari mereka kita bisa meng-explore profilenya, dan melihat lebih jauh tentang hal-hal baru yang mungkin kita belum pernah tahu sebelumnya.

4. **Membantu Komunitas**: Selain itu kita juga bisa memberikan kontribusi positif pada komunitas, dan ada kalanya kita perlu untuk membantu mereka terlebih apabila kita memiliki problem di plugin yang kita gunakan. Sebagai contoh, dalam lingkungan kerja kita menggunakan plugin django-rest-framework, tapi ternyata ada bug disana, dan belum ada fixes'nya, sementara kita tahu bagaimana nge-fix'nya. Nah, disitulah peran kita dibutuhkan, toh itu kembalinya untuk kita sendiri kan? 😁 

---------------

Dan, dibawah ini beberapa tips yang mungkin bisa diterapkan:

1. Pilih proyek open source yang sesuai dengan minat dan keterampilan kita.
2. Pelajari Dokumentasi, Kode dan cara kerja'nya (jika kita berkontribusi di project lain)
3. Pelajari Git dan GitHub atau sejenisnya
4. Mulai dengan hal-hal / project2 yang kecil (contohnya seperti kalkulator, countdown, webtools, dll)
5. Luangkan sedikit waktu dari waktu2 luang yang kita miliki.
6. Sabar dan jangan menyerah, ini yang lmyan sulit.
7. Ingat kata pepatah, kita berbuat baik akan kembali baik 😁

**Comment by cahyareza** [comment]
Terimakasih tipsnya mas.
Sama satu lagi apakah wothed belajar membuat standalone app in django? Saya liat mas banyak buat package atau module gt, kayaknya sama konsepnya dengan standalone app. Termiakasih

**Comment by agusmakmun** [comment]
@cahyareza tergantung skala project'nya mas, kebetulan yang saya share disini umumnya standalone app, yang mungkin bisa bermanfaat sebagai bahan belajar..

terkait dengan apakah worth it atau tdknya, aku bisa bilang itu worth secara tdk langsung..
