### ISSUE TITLE
hi im a student from chile 

### ISSUE THREAD

**Issue by Gab-ORo** [agusmakmun/askme#2]
i have a question for u... im question at chatgpt for a engine or app for training a CNN and the response give me your profile on github... the question is, here i can take the code for this job ? 

PD: sorry for my bad inglish
![image](https://user-images.githubusercontent.com/126223028/234043731-daf6e10e-f3b4-4502-8f1c-a23c6258008a.png)
if u can help me with any info i will glad u

**Comment by agusmakmun** [comment]
Hello @Gab-ORo, seems chatgpt response the wrong answer, I didn't have that repository.

But here is some similar repos that you may looking for:
- https://github.com/agusmakmun/PySastrawi
- https://github.com/agusmakmun/SentiStrengthID

Thank you..
